# -*- coding: utf-8 -*-
"""3.1 Modelos ARIMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1miWluulH9xCZvm9wGn5pR8FwpSKt7B4f
"""

# -*- coding: utf-8 -*-
"""Stock Analysis - Random Walk, Unit Root, Cointegration, and ARIMA.ipynb

Automatically generated by Colab.
"""

# Import required libraries
import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt

# Upload single Excel file
print("Please upload the Excel file containing JNJ, XOM, and NVDA data")
upload = files.upload()
filename = list(upload.keys())[0]

# Read the Excel file
df = pd.read_excel(filename, header=0)

# Print the first few rows to inspect the data
print("\nFirst few rows of the DataFrame:")
print(df.head())

# Print available columns to confirm
print("\nDataFrame columns:", list(df.columns))

# Debug: Print the raw data in the columns we're extracting
print("\nRaw JNJ Close (Column C, index 2):")
print(df.iloc[:, 2].head())
print("\nRaw XOM Close (Column G, index 6):")
print(df.iloc[:, 6].head())
print("\nRaw NVDA Close (Column J, index 10):")
print(df.iloc[:, 10].head())

# Since the date column is already in datetime format, use it directly as the index
df['DateTime'] = df.iloc[:, 0]
df.set_index('DateTime', inplace=True)

# Extract closing prices using the correct column indices
try:
    jnj_close = df.iloc[:, 2]    # Column C (index 2) - JNJ Close
    xom_close = df.iloc[:, 6]    # Column G (index 6) - XOM Close
    nvda_close = df.iloc[:, 10]  # Column J (index 10) - NVDA Close
except IndexError as e:
    print(f"Error: Column index out of range - {e}")
    print("Available columns:", list(df.columns))
    print("Please check the column indices and try again")
    raise

# Convert series to numeric, coercing errors to NaN
jnj_close = pd.to_numeric(jnj_close, errors='coerce')
xom_close = pd.to_numeric(xom_close, errors='coerce')
nvda_close = pd.to_numeric(nvda_close, errors='coerce')

# Forward fill missing values to align series
jnj_close = jnj_close.ffill()
xom_close = xom_close.ffill()
nvda_close = nvda_close.ffill()

# Drop any remaining NaN values
jnj_close = jnj_close.dropna()
xom_close = xom_close.dropna()
nvda_close = nvda_close.dropna()

# Debug: Check the data after numeric conversion
print("\nJNJ Close after numeric conversion (first 5 rows):")
print(jnj_close.head())
print("\nXOM Close after numeric conversion (first 5 rows):")
print(xom_close.head())
print("\nNVDA Close after numeric conversion (first 5 rows):")
print(nvda_close.head())

# Debug: Check the length of each series after cleaning
print(f"\nLength of JNJ series after cleaning: {len(jnj_close)}")
print(f"Length of XOM series after cleaning: {len(xom_close)}")
print(f"Length of NVDA series after cleaning: {len(nvda_close)}")

# Check if any series is empty
if len(jnj_close) == 0 or len(xom_close) == 0 or len(nvda_close) == 0:
    raise ValueError("One or more series are empty after cleaning. Please check the data for non-numeric values or missing data.")

# Ensure all series have the same length
min_length = min(len(jnj_close), len(xom_close), len(nvda_close))
jnj_close = jnj_close.iloc[:min_length]
xom_close = xom_close.iloc[:min_length]
nvda_close = nvda_close.iloc[:min_length]

# Verify that the series are numeric
if not (jnj_close.dtype in [np.float64, np.int64] and
        xom_close.dtype in [np.float64, np.int64] and
        nvda_close.dtype in [np.float64, np.int64]):
    raise ValueError("One or more series contain non-numeric data after cleaning")

# Function for unit root tests with detailed interpretation, including Random Walk
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
        print(f"    Implication: {name} does not have a unit root and is suitable for modeling without differencing.")
        print(f"    Random Walk: {name} does NOT follow a Random Walk (since it is stationary).")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")
        print(f"    Implication: {name} may have a unit root; consider differencing or further analysis.")
        print(f"    Random Walk: {name} may follow a Random Walk (since it has a unit root).")

    # KPSS Test
    kpss_result = kpss(series)
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
        print(f"    Implication: {name} may require differencing to achieve stationarity for modeling.")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")
        print(f"    Implication: {name} appears stationary and may not need differencing.")

    # Combined Interpretation
    print("\nCombined Interpretation:")
    if adf_result[1] < 0.05 and kpss_result[1] >= 0.05:
        print(f"  - Both tests agree: {name} is stationary. Suitable for modeling as-is.")
        print(f"    Random Walk Conclusion: {name} does NOT follow a Random Walk.")
    elif adf_result[1] >= 0.05 and kpss_result[1] < 0.05:
        print(f"  - Both tests agree: {name} is non-stationary. Differencing or transformation may be required.")
        print(f"    Random Walk Conclusion: {name} likely follows a Random Walk.")
    else:
        print(f"  - Tests disagree: Mixed evidence on stationarity for {name}. Consider further analysis (e.g., differencing, trend analysis).")
        print(f"    Random Walk Conclusion: Uncertain - further analysis needed to determine if {name} follows a Random Walk.")

# Perform unit root tests on original series
unit_root_tests(jnj_close, "JNJ")
unit_root_tests(xom_close, "XOM")
unit_root_tests(nvda_close, "NVDA")

# Cointegration test with detailed interpretation
def cointegration_test(df):
    result = coint_johansen(df, det_order=0, k_ar_diff=1)
    print("\nJohansen Cointegration Test (JNJ, XOM, NVDA):")
    print(f"Trace statistic: {result.lr1}")
    print(f"Critical values (90%, 95%, 99%): {result.cvt}")
    print("Interpretation:")
    for i in range(len(result.lr1)):
        if result.lr1[i] > result.cvt[i, 1]:
            print(f"  - r = {i}: Cointegration exists at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
        else:
            print(f"  - r = {i}: No cointegration at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
    if result.lr1[0] > result.cvt[0, 1]:
        print("Conclusion: JNJ, XOM, and NVDA are cointegrated - they share a long-run equilibrium relationship.")
        print("Implication: These series move together over the long term; consider a Vector Error Correction Model (VECM) for forecasting.")
    else:
        print("Conclusion: No evidence of cointegration among JNJ, XOM, and NVDA.")
        print("Implication: These series do not share a long-run relationship; model them separately (e.g., using ARIMA).")

# Prepare data for cointegration using original series
coint_df = pd.DataFrame({
    'JNJ': jnj_close,
    'XOM': xom_close,
    'NVDA': nvda_close
}).dropna()
cointegration_test(coint_df)

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA models on original series
jnj_order = find_best_arima(jnj_close, "JNJ")
xom_order = find_best_arima(xom_close, "XOM")
nvda_order = find_best_arima(nvda_close, "NVDA")

# Fit final ARIMA models
jnj_model = ARIMA(jnj_close, order=jnj_order).fit()
xom_model = ARIMA(xom_close, order=xom_order).fit()
nvda_model = ARIMA(nvda_close, order=nvda_order).fit()

# Forecast next 30 periods (5-minute intervals, so 30 periods = 150 minutes)
forecast_steps = 30
jnj_forecast = jnj_model.forecast(steps=forecast_steps)
xom_forecast = xom_model.forecast(steps=forecast_steps)
nvda_forecast = nvda_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(jnj_close) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Transform data and forecasts to log10 scale for plotting
jnj_close_log = np.log10(jnj_close)
xom_close_log = np.log10(xom_close)
nvda_close_log = np.log10(nvda_close)
jnj_forecast_log = np.log10(jnj_forecast)
xom_forecast_log = np.log10(xom_forecast)
nvda_forecast_log = np.log10(nvda_forecast)

# Plot original series with forecasts in log10 scale
plt.figure(figsize=(12,6))
plt.plot(jnj_close_log, label='JNJ Historical (log10)', color='blue')
plt.plot(forecast_index, jnj_forecast_log, label='JNJ Forecast (log10)', color='red')
plt.plot(xom_close_log, label='XOM Historical (log10)', color='green')
plt.plot(forecast_index, xom_forecast_log, label='XOM Forecast (log10)', color='orange')
plt.plot(nvda_close_log, label='NVDA Historical (log10)', color='purple')
plt.plot(forecast_index, nvda_forecast_log, label='NVDA Forecast (log10)', color='pink')
plt.title('JNJ, XOM, and NVDA Closing Prices with Forecasts (log10 Scale)')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    # Generate forecast
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    # Transform to log10 scale for plotting
    series_log = np.log10(series)
    forecast_log = np.log10(forecast)
    conf_int_log = np.log10(conf_int)

    forecast_index = range(len(series), len(series) + steps)

    # Plot in log10 scale
    plt.figure(figsize=(12,6))
    plt.plot(series_log, label=f'{name} Historical (log10)', color='blue')
    plt.plot(forecast_index, forecast_log, label='Forecast (log10)', color='red')
    plt.fill_between(forecast_index,
                    conf_int_log.iloc[:, 0],
                    conf_int_log.iloc[:, 1],
                    color='pink',
                    alpha=0.3,
                    label='95% Confidence Interval (log10)')
    plt.title(f'{name} Price Forecast (log10 Scale)')
    plt.legend()
    plt.show()

    # Forecast interpretation in original scale
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name} (Original Scale):")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps} (Original Scale): [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
plot_forecast(jnj_model, jnj_close, "JNJ")
plot_forecast(xom_model, xom_close, "XOM")
plot_forecast(nvda_model, nvda_close, "NVDA")

# Print forecast values in original scale
print("\nJNJ Forecast Values (next 5 periods, Original Scale):")
print(jnj_forecast[:5])
print("\nXOM Forecast Values (next 5 periods, Original Scale):")
print(xom_forecast[:5])
print("\nNVDA Forecast Values (next 5 periods, Original Scale):")
print(nvda_forecast[:5])

# -*- coding: utf-8 -*-
"""Stock Analysis - Random Walk, Unit Root, Cointegration, and ARIMA.ipynb

Automatically generated by Colab.
"""

# Import required libraries
import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt

# Upload single Excel file
print("Please upload the Excel file containing JNJ, XOM, and NVDA data")
upload = files.upload()
filename = list(upload.keys())[0]

# Read the Excel file
df = pd.read_excel(filename, header=0)

# Print the first few rows to inspect the data
print("\nFirst few rows of the DataFrame:")
print(df.head())

# Print available columns to confirm
print("\nDataFrame columns:", list(df.columns))

# Debug: Print the raw data in the columns we're extracting
print("\nRaw JNJ Close (Column C, index 2):")
print(df.iloc[:, 2].head())
print("\nRaw XOM Close (Column G, index 6):")
print(df.iloc[:, 6].head())
print("\nRaw NVDA Close (Column J, index 10):")
print(df.iloc[:, 10].head())

# Since the date column is already in datetime format, use it directly as the index
df['DateTime'] = df.iloc[:, 0]
df.set_index('DateTime', inplace=True)

# Extract closing prices using the correct column indices
try:
    jnj_close = df.iloc[:, 2]    # Column C (index 2) - JNJ Close
    xom_close = df.iloc[:, 6]    # Column G (index 6) - XOM Close
    nvda_close = df.iloc[:, 10]  # Column J (index 10) - NVDA Close
except IndexError as e:
    print(f"Error: Column index out of range - {e}")
    print("Available columns:", list(df.columns))
    print("Please check the column indices and try again")
    raise

# Convert series to numeric, coercing errors to NaN
jnj_close = pd.to_numeric(jnj_close, errors='coerce')
xom_close = pd.to_numeric(xom_close, errors='coerce')
nvda_close = pd.to_numeric(nvda_close, errors='coerce')

# Forward fill missing values to align series
jnj_close = jnj_close.ffill()
xom_close = xom_close.ffill()
nvda_close = nvda_close.ffill()

# Drop any remaining NaN values
jnj_close = jnj_close.dropna()
xom_close = xom_close.dropna()
nvda_close = nvda_close.dropna()

# Debug: Check the data after numeric conversion
print("\nJNJ Close after numeric conversion (first 5 rows):")
print(jnj_close.head())
print("\nXOM Close after numeric conversion (first 5 rows):")
print(xom_close.head())
print("\nNVDA Close after numeric conversion (first 5 rows):")
print(nvda_close.head())

# Debug: Check the length of each series after cleaning
print(f"\nLength of JNJ series after cleaning: {len(jnj_close)}")
print(f"Length of XOM series after cleaning: {len(xom_close)}")
print(f"Length of NVDA series after cleaning: {len(nvda_close)}")

# Check if any series is empty
if len(jnj_close) == 0 or len(xom_close) == 0 or len(nvda_close) == 0:
    raise ValueError("One or more series are empty after cleaning. Please check the data for non-numeric values or missing data.")

# Ensure all series have the same length
min_length = min(len(jnj_close), len(xom_close), len(nvda_close))
jnj_close = jnj_close.iloc[:min_length]
xom_close = xom_close.iloc[:min_length]
nvda_close = nvda_close.iloc[:min_length]

# Verify that the series are numeric
if not (jnj_close.dtype in [np.float64, np.int64] and
        xom_close.dtype in [np.float64, np.int64] and
        nvda_close.dtype in [np.float64, np.int64]):
    raise ValueError("One or more series contain non-numeric data after cleaning")

# Function for unit root tests with detailed interpretation, including Random Walk
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
        print(f"    Implication: {name} does not have a unit root and is suitable for modeling without differencing.")
        print(f"    Random Walk: {name} does NOT follow a Random Walk (since it is stationary).")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")
        print(f"    Implication: {name} may have a unit root; consider differencing or further analysis.")
        print(f"    Random Walk: {name} may follow a Random Walk (since it has a unit root).")

    # KPSS Test
    kpss_result = kpss(series)
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
        print(f"    Implication: {name} may require differencing to achieve stationarity for modeling.")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")
        print(f"    Implication: {name} appears stationary and may not need differencing.")

    # Combined Interpretation
    print("\nCombined Interpretation:")
    if adf_result[1] < 0.05 and kpss_result[1] >= 0.05:
        print(f"  - Both tests agree: {name} is stationary. Suitable for modeling as-is.")
        print(f"    Random Walk Conclusion: {name} does NOT follow a Random Walk.")
    elif adf_result[1] >= 0.05 and kpss_result[1] < 0.05:
        print(f"  - Both tests agree: {name} is non-stationary. Differencing or transformation may be required.")
        print(f"    Random Walk Conclusion: {name} likely follows a Random Walk.")
    else:
        print(f"  - Tests disagree: Mixed evidence on stationarity for {name}. Consider further analysis (e.g., differencing, trend analysis).")
        print(f"    Random Walk Conclusion: Uncertain - further analysis needed to determine if {name} follows a Random Walk.")

# Perform unit root tests on original series
unit_root_tests(jnj_close, "JNJ")
unit_root_tests(xom_close, "XOM")
unit_root_tests(nvda_close, "NVDA")

# Cointegration test with detailed interpretation
def cointegration_test(df):
    result = coint_johansen(df, det_order=0, k_ar_diff=1)
    print("\nJohansen Cointegration Test (JNJ, XOM, NVDA):")
    print(f"Trace statistic: {result.lr1}")
    print(f"Critical values (90%, 95%, 99%): {result.cvt}")
    print("Interpretation:")
    for i in range(len(result.lr1)):
        if result.lr1[i] > result.cvt[i, 1]:
            print(f"  - r = {i}: Cointegration exists at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
        else:
            print(f"  - r = {i}: No cointegration at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
    if result.lr1[0] > result.cvt[0, 1]:
        print("Conclusion: JNJ, XOM, and NVDA are cointegrated - they share a long-run equilibrium relationship.")
        print("Implication: These series move together over the long term; consider a Vector Error Correction Model (VECM) for forecasting.")
    else:
        print("Conclusion: No evidence of cointegration among JNJ, XOM, and NVDA.")
        print("Implication: These series do not share a long-run relationship; model them separately (e.g., using ARIMA).")

# Prepare data for cointegration using original series
coint_df = pd.DataFrame({
    'JNJ': jnj_close,
    'XOM': xom_close,
    'NVDA': nvda_close
}).dropna()
cointegration_test(coint_df)

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA models on original series
jnj_order = find_best_arima(jnj_close, "JNJ")
xom_order = find_best_arima(xom_close, "XOM")
nvda_order = find_best_arima(nvda_close, "NVDA")

# Fit final ARIMA models
jnj_model = ARIMA(jnj_close, order=jnj_order).fit()
xom_model = ARIMA(xom_close, order=xom_order).fit()
nvda_model = ARIMA(nvda_close, order=nvda_order).fit()

# Forecast next 30 periods (5-minute intervals, so 30 periods = 150 minutes)
forecast_steps = 30
jnj_forecast = jnj_model.forecast(steps=forecast_steps)
xom_forecast = xom_model.forecast(steps=forecast_steps)
nvda_forecast = nvda_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(jnj_close) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Transform data and forecasts to log10 scale for plotting
jnj_close_log = np.log10(jnj_close)
xom_close_log = np.log10(xom_close)
nvda_close_log = np.log10(nvda_close)
jnj_forecast_log = np.log10(jnj_forecast)
xom_forecast_log = np.log10(xom_forecast)
nvda_forecast_log = np.log10(nvda_forecast)

# Plot original series with forecasts in log10 scale
plt.figure(figsize=(12,6))
plt.plot(jnj_close_log, label='JNJ Historical (log10)', color='blue')
plt.plot(forecast_index, jnj_forecast_log, label='JNJ Forecast (log10)', color='red')
plt.plot(xom_close_log, label='XOM Historical (log10)', color='green')
plt.plot(forecast_index, xom_forecast_log, label='XOM Forecast (log10)', color='orange')
plt.plot(nvda_close_log, label='NVDA Historical (log10)', color='purple')
plt.plot(forecast_index, nvda_forecast_log, label='NVDA Forecast (log10)', color='pink')
plt.title('JNJ, XOM, and NVDA Closing Prices with Forecasts (log10 Scale)')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    # Generate forecast
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    # Transform to log10 scale for plotting
    series_log = np.log10(series)
    forecast_log = np.log10(forecast)
    conf_int_log = np.log10(conf_int)

    forecast_index = range(len(series), len(series) + steps)

    # Plot in log10 scale
    plt.figure(figsize=(12,6))
    plt.plot(series_log, label=f'{name} Historical (log10)', color='blue')
    plt.plot(forecast_index, forecast_log, label='Forecast (log10)', color='red')
    plt.fill_between(forecast_index,
                    conf_int_log.iloc[:, 0],
                    conf_int_log.iloc[:, 1],
                    color='pink',
                    alpha=0.3,
                    label='95% Confidence Interval (log10)')
    plt.title(f'{name} Price Forecast (log10 Scale)')
    plt.legend()
    plt.show()

    # Forecast interpretation in original scale
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name} (Original Scale):")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps} (Original Scale): [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
plot_forecast(jnj_model, jnj_close, "JNJ")
plot_forecast(xom_model, xom_close, "XOM")
plot_forecast(nvda_model, nvda_close, "NVDA")

# Print forecast values in original scale
print("\nJNJ Forecast Values (next 5 periods, Original Scale):")
print(jnj_forecast[:5])
print("\nXOM Forecast Values (next 5 periods, Original Scale):")
print(xom_forecast[:5])
print("\nNVDA Forecast Values (next 5 periods, Original Scale):")
print(nvda_forecast[:5])